var jsPaths_2 = { // add to all paths_*.js those lines: "groupPathsJSonName": "jsPaths_*" and "groupPathsName": "paths_*"
  "ns0:svg": {
    "groupPathsJSonName": "jsPaths_2",
    "groupPathsName": "paths_2",
    "-xmlns:ns0": "http://www.w3.org/2000/svg",
    "-enable-background": "new 0 0 612 792",
    "-height": "792px",
    "-id": "Layer_1",
    "-version": "1.1",
    "-viewBox": "0 0 612 792",
    "-width": "612px",
    "-x": "0px",
    "-y": "0px",
    "-xml:space": "preserve",
    "ns0:g": {
      "-id": "Layer_3_1_",
      "ns0:g": {
        "-id": "Layer_2",
        "ns0:line": [
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.292",
            "-x2": "221.125",
            "-y1": "681.983",
            "-y2": "725.957"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.292",
            "-x2": "186.431",
            "-y1": "681.983",
            "-y2": "681.983"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.431",
            "-x2": "186.265",
            "-y1": "681.983",
            "-y2": "659.95"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.265",
            "-x2": "87.668",
            "-y1": "659.95",
            "-y2": "659.932"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.063",
            "-y1": "659.932",
            "-y2": "680.566"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.063",
            "-x2": "19.835",
            "-y1": "680.566",
            "-y2": "680.566"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.668",
            "-y1": "659.932",
            "-y2": "649.305"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "19.995",
            "-y1": "649.305",
            "-y2": "649.305"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.668",
            "-y1": "649.305",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "68.912",
            "-y1": "589.485",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "123.514",
            "-y1": "589.485",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.265",
            "-x2": "218.429",
            "-y1": "659.95",
            "-y2": "659.932"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "218.429",
            "-y1": "659.932",
            "-y2": "622.732"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "474.531",
            "-y1": "622.732",
            "-y2": "622.732"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "218.429",
            "-y1": "622.732",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "93.551",
            "-y1": "548.727",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "93.551",
            "-y1": "548.727",
            "-y2": "436.597"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "17.482",
            "-y1": "436.597",
            "-y2": "436.597"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "93.551",
            "-y1": "436.597",
            "-y2": "377.854"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "132.758",
            "-y1": "377.854",
            "-y2": "377.854"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "132.758",
            "-x2": "132.758",
            "-y1": "377.854",
            "-y2": "323.446"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.865",
            "-x2": "177.868",
            "-y1": "548.727",
            "-y2": "250.31"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.868",
            "-x2": "36.373",
            "-y1": "250.31",
            "-y2": "250.31"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "250.312",
            "-y2": "279.86"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "18.15",
            "-y1": "279.86",
            "-y2": "279.86"
          }
        ]
      }
    }
  }
}