var jsPaths_1 = { // add to all paths_*.js those lines: "groupPathsJSonName": "jsPaths_*" and "groupPathsName": "paths_*"
  "ns0:svg": {
    "groupPathsJSonName": "jsPaths_1",
    "groupPathsName": "paths_1",
    "-xmlns:ns0": "http://www.w3.org/2000/svg",
    "-enable-background": "new 0 0 612 792",
    "-height": "792px",
    "-id": "Layer_1",
    "-version": "1.1",
    "-viewBox": "0 0 612 792",
    "-width": "612px",
    "-x": "0px",
    "-y": "0px",
    "-xml:space": "preserve",
    "ns0:g": {
      "-id": "Layer_3_1_",
      "ns0:g": {
        "-id": "Layer_2",
        "ns0:line": [
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.292",
            "-x2": "221.125",
            "-y1": "681.983",
            "-y2": "725.957"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.292",
            "-x2": "186.431",
            "-y1": "681.983",
            "-y2": "681.983"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.431",
            "-x2": "186.265",
            "-y1": "681.983",
            "-y2": "659.95"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.265",
            "-x2": "87.668",
            "-y1": "659.95",
            "-y2": "659.932"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.063",
            "-y1": "659.932",
            "-y2": "680.566"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.063",
            "-x2": "19.835",
            "-y1": "680.566",
            "-y2": "680.566"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.668",
            "-y1": "659.932",
            "-y2": "649.305"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "19.995",
            "-y1": "649.305",
            "-y2": "649.305"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "87.668",
            "-y1": "649.305",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "68.912",
            "-y1": "589.485",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.668",
            "-x2": "123.514",
            "-y1": "589.485",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.265",
            "-x2": "218.429",
            "-y1": "659.95",
            "-y2": "659.932"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "218.429",
            "-y1": "659.932",
            "-y2": "622.732"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "474.531",
            "-y1": "622.732",
            "-y2": "622.732"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "218.429",
            "-y1": "622.732",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "93.551",
            "-y1": "548.727",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "93.551",
            "-y1": "548.727",
            "-y2": "436.597"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "17.482",
            "-y1": "436.597",
            "-y2": "436.597"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "93.551",
            "-y1": "436.597",
            "-y2": "377.854"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.551",
            "-x2": "132.758",
            "-y1": "377.854",
            "-y2": "377.854"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "132.758",
            "-x2": "132.758",
            "-y1": "377.854",
            "-y2": "323.446"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.865",
            "-x2": "177.868",
            "-y1": "548.727",
            "-y2": "250.31"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.868",
            "-x2": "36.373",
            "-y1": "250.31",
            "-y2": "250.31"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "250.312",
            "-y2": "279.86"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "18.15",
            "-y1": "279.86",
            "-y2": "279.86"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "37.508",
            "-y1": "188.304",
            "-y2": "188.304"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "188.304",
            "-y2": "166.449"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "21.775",
            "-y1": "166.449",
            "-y2": "166.449"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "166.449",
            "-y2": "135.198"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "21.775",
            "-y1": "135.198",
            "-y2": "135.198"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "135.198",
            "-y2": "117.991"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "26.355",
            "-y1": "117.991",
            "-y2": "117.991"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "218.429",
            "-x2": "282.757",
            "-y1": "548.727",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "282.757",
            "-y1": "548.727",
            "-y2": "508.374"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "226.81",
            "-y1": "508.374",
            "-y2": "508.374"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "226.81",
            "-x2": "226.81",
            "-y1": "508.374",
            "-y2": "409.357"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "250.593",
            "-x2": "250.593",
            "-y1": "508.374",
            "-y2": "408.355"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "282.757",
            "-y1": "508.374",
            "-y2": "323.446"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "215.266",
            "-y1": "323.446",
            "-y2": "323.446"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "282.757",
            "-y1": "323.446",
            "-y2": "272.755"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "222.898",
            "-y1": "272.755",
            "-y2": "272.755"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "282.757",
            "-x2": "320.632",
            "-y1": "548.727",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.632",
            "-x2": "320.632",
            "-y1": "548.727",
            "-y2": "539.448"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.632",
            "-x2": "389.469",
            "-y1": "539.448",
            "-y2": "539.259"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "389.469",
            "-y1": "539.259",
            "-y2": "589.485"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "389.469",
            "-y1": "539.259",
            "-y2": "499.472"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "355.051",
            "-y1": "499.472",
            "-y2": "499.472"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "355.051",
            "-x2": "355.051",
            "-y1": "499.472",
            "-y2": "530.717"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "389.469",
            "-y1": "499.472",
            "-y2": "425.72"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "330.234",
            "-y1": "425.72",
            "-y2": "425.72"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "389.469",
            "-y1": "425.72",
            "-y2": "308.367"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "389.469",
            "-x2": "320.031",
            "-y1": "308.367",
            "-y2": "308.367"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.031",
            "-x2": "320.031",
            "-y1": "308.367",
            "-y2": "235.973"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.031",
            "-x2": "393.323",
            "-y1": "235.973",
            "-y2": "235.973"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.031",
            "-x2": "320.031",
            "-y1": "235.973",
            "-y2": "205.758"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.031",
            "-x2": "393.323",
            "-y1": "205.758",
            "-y2": "205.758"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.868",
            "-x2": "177.868",
            "-y1": "250.31",
            "-y2": "143.499"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.868",
            "-x2": "208.509",
            "-y1": "143.499",
            "-y2": "143.499"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.509",
            "-x2": "208.509",
            "-y1": "143.499",
            "-y2": "120.219"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.509",
            "-x2": "285.354",
            "-y1": "120.219",
            "-y2": "120.219"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.509",
            "-x2": "301.611",
            "-y1": "143.499",
            "-y2": "143.499"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.509",
            "-x2": "208.509",
            "-y1": "143.499",
            "-y2": "167.737"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.509",
            "-x2": "287.3",
            "-y1": "167.737",
            "-y2": "167.737"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "301.611",
            "-x2": "301.611",
            "-y1": "143.499",
            "-y2": "158.678"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "301.611",
            "-x2": "370.306",
            "-y1": "158.678",
            "-y2": "158.678"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "301.611",
            "-x2": "301.611",
            "-y1": "143.499",
            "-y2": "126.211"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "301.611",
            "-x2": "474.531",
            "-y1": "126.211",
            "-y2": "126.211"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "474.531",
            "-x2": "516.281",
            "-y1": "548.727",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "516.281",
            "-x2": "516.281",
            "-y1": "548.727",
            "-y2": "561.473"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "516.281",
            "-x2": "552.093",
            "-y1": "561.473",
            "-y2": "561.473"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "552.093",
            "-y1": "561.473",
            "-y2": "591.281"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "516.281",
            "-y1": "591.281",
            "-y2": "591.281"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "590.74",
            "-y1": "591.281",
            "-y2": "591.281"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "590.511",
            "-y1": "561.473",
            "-y2": "561.473"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "552.093",
            "-y1": "561.473",
            "-y2": "532.967"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "590.511",
            "-y1": "532.967",
            "-y2": "532.967"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "552.093",
            "-y1": "532.967",
            "-y2": "495.303"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "578.448",
            "-y1": "495.303",
            "-y2": "495.162"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "552.093",
            "-y1": "495.303",
            "-y2": "460.521"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "590.511",
            "-y1": "460.521",
            "-y2": "460.521"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "552.093",
            "-y1": "460.521",
            "-y2": "431.062"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "590.511",
            "-y1": "431.062",
            "-y2": "431.062"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "552.093",
            "-x2": "521.649",
            "-y1": "431.062",
            "-y2": "431.062"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "555.823",
            "-y1": "422.977",
            "-y2": "403.105"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "521.649",
            "-y1": "403.105",
            "-y2": "403.105"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "590.511",
            "-y1": "403.105",
            "-y2": "403.105"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "555.823",
            "-y1": "403.105",
            "-y2": "383.567"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "474.531",
            "-x2": "474.531",
            "-y1": "622.732",
            "-y2": "548.727"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "474.531",
            "-x2": "474.531",
            "-y1": "548.727",
            "-y2": "383.567"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "474.531",
            "-x2": "474.531",
            "-y1": "383.567",
            "-y2": "126.211"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "555.823",
            "-y1": "383.567",
            "-y2": "344.217"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "521.649",
            "-y1": "344.217",
            "-y2": "344.217"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "591.227",
            "-y1": "344.217",
            "-y2": "344.217"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "555.823",
            "-x2": "510.448",
            "-y1": "319.386",
            "-y2": "319.386"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "510.448",
            "-x2": "510.448",
            "-y1": "319.386",
            "-y2": "383.567"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "510.448",
            "-x2": "474.531",
            "-y1": "383.567",
            "-y2": "383.567"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "510.448",
            "-x2": "555.823",
            "-y1": "383.567",
            "-y2": "383.567"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "474.531",
            "-x2": "562.313",
            "-y1": "243.604",
            "-y2": "243.604"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "562.313",
            "-y1": "243.604",
            "-y2": "194.257"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "595.99",
            "-y1": "194.257",
            "-y2": "194.257"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "562.313",
            "-y1": "194.257",
            "-y2": "164.733"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "594.565",
            "-y1": "164.733",
            "-y2": "164.733"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "562.313",
            "-y1": "164.733",
            "-y2": "125.709"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "593.767",
            "-y1": "125.709",
            "-y2": "125.709"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "562.313",
            "-x2": "562.313",
            "-y1": "125.709",
            "-y2": "100.899"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "513.916",
            "-y1": "243.604",
            "-y2": "222.816"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "550.438",
            "-y1": "222.816",
            "-y2": "222.816"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "513.916",
            "-y1": "222.816",
            "-y2": "197.395"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "550.594",
            "-y1": "197.395",
            "-y2": "197.395"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "513.916",
            "-y1": "197.395",
            "-y2": "161.883"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "550.594",
            "-y1": "161.883",
            "-y2": "161.883"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "513.916",
            "-y1": "161.883",
            "-y2": "127.458"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "550.594",
            "-y1": "127.458",
            "-y2": "127.458"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "513.916",
            "-x2": "513.916",
            "-y1": "127.458",
            "-y2": "100.684"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "188.304",
            "-y2": "213.755"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "25.974",
            "-y1": "213.755",
            "-y2": "213.755"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "135.163",
            "-x2": "135.163",
            "-y1": "213.755",
            "-y2": "250.312"
          }
        ]
      }
    }
  }
}